#!/usr/bin/env bash
# xcode-setup.sh — AeroDrop macOS
# Run once after cloning to install OpenSSL and print the Xcode build settings
# you need to configure manually (or patch via xcodebuild / sed below).
#
# Usage:
#   chmod +x xcode-setup.sh
#   ./xcode-setup.sh
#
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; RESET='\033[0m'
info()  { echo -e "${CYAN}[AeroDrop]${RESET} $*"; }
ok()    { echo -e "${GREEN}[  OK   ]${RESET} $*"; }
warn()  { echo -e "${YELLOW}[ WARN  ]${RESET} $*"; }
error() { echo -e "${RED}[ ERROR ]${RESET} $*"; exit 1; }

# ── 1. Check Homebrew ─────────────────────────────────────────────────────────
info "Checking Homebrew…"
if ! command -v brew &>/dev/null; then
    error "Homebrew not found. Install from https://brew.sh and re-run."
fi
ok "Homebrew found: $(brew --version | head -1)"

# ── 2. Install / verify OpenSSL ───────────────────────────────────────────────
info "Installing OpenSSL 3 via Homebrew…"
brew install openssl@3 2>/dev/null || true

OPENSSL_PREFIX="$(brew --prefix openssl@3)"
if [[ ! -d "$OPENSSL_PREFIX" ]]; then
    error "OpenSSL prefix not found at $OPENSSL_PREFIX"
fi
ok "OpenSSL prefix: $OPENSSL_PREFIX"

OPENSSL_VERSION="$("$OPENSSL_PREFIX/bin/openssl" version)"
ok "OpenSSL version: $OPENSSL_VERSION"

# ── 3. Detect architecture ────────────────────────────────────────────────────
ARCH="$(uname -m)"
info "Host architecture: $ARCH"
if [[ "$ARCH" == "arm64" ]]; then
    ok "Apple Silicon — will build arm64 slice."
else
    ok "Intel — will build x86_64 slice."
fi

# ── 4. Print the Xcode build settings to configure ───────────────────────────
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════════${RESET}"
echo -e "${CYAN}  Xcode Build Settings  (Project → Build Settings)        ${RESET}"
echo -e "${CYAN}══════════════════════════════════════════════════════════${RESET}"
echo ""
echo -e "${YELLOW}  HEADER_SEARCH_PATHS${RESET}"
echo "    \$(inherited)"
echo "    $OPENSSL_PREFIX/include"
echo ""
echo -e "${YELLOW}  LIBRARY_SEARCH_PATHS${RESET}"
echo "    \$(inherited)"
echo "    $OPENSSL_PREFIX/lib"
echo ""
echo -e "${YELLOW}  OTHER_LDFLAGS${RESET}"
echo "    \$(inherited) -lssl -lcrypto"
echo ""
echo -e "${YELLOW}  SWIFT_OBJC_BRIDGING_HEADER${RESET}"
echo "    AeroDrop/AeroDrop-Bridging-Header.h"
echo ""
echo -e "${YELLOW}  CLANG_CXX_LANGUAGE_STANDARD${RESET}"
echo "    c++20"
echo ""
echo -e "${YELLOW}  MACOSX_DEPLOYMENT_TARGET${RESET}"
echo "    13.0"
echo ""
echo -e "${YELLOW}  GCC_PREPROCESSOR_DEFINITIONS  (Debug)${RESET}"
echo "    DEBUG=1 \$(inherited)"
echo ""
echo -e "${YELLOW}  CODE_SIGN_ENTITLEMENTS${RESET}"
echo "    AeroDrop/AeroDrop.entitlements"
echo ""
echo -e "${YELLOW}  INFOPLIST_FILE${RESET}"
echo "    AeroDrop/Info.plist"
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════════════${RESET}"
echo ""

# ── 5. Auto-patch via xcodebuild xcconfig ────────────────────────────────────
XCCONFIG_PATH="$(dirname "$0")/AeroDrop.xcconfig"

cat > "$XCCONFIG_PATH" <<XCCONFIG
// AeroDrop.xcconfig — auto-generated by xcode-setup.sh
// Add this to your target under:
//   Project → Info → Configurations → Debug / Release → AeroDrop

HEADER_SEARCH_PATHS          = \$(inherited) "${OPENSSL_PREFIX}/include"
LIBRARY_SEARCH_PATHS         = \$(inherited) "${OPENSSL_PREFIX}/lib"
OTHER_LDFLAGS                = \$(inherited) -lssl -lcrypto
SWIFT_OBJC_BRIDGING_HEADER   = AeroDrop/AeroDrop-Bridging-Header.h
CLANG_CXX_LANGUAGE_STANDARD  = c++20
MACOSX_DEPLOYMENT_TARGET     = 13.0
CODE_SIGN_ENTITLEMENTS        = AeroDrop/AeroDrop.entitlements
INFOPLIST_FILE                = AeroDrop/Info.plist
XCCONFIG

ok "Generated AeroDrop.xcconfig → $XCCONFIG_PATH"
echo ""
echo -e "${CYAN}Next steps:${RESET}"
echo "  1. Open AeroDrop.xcodeproj in Xcode"
echo "  2. Click the project in the Navigator → select the AeroDrop target"
echo "  3. Info tab → Configurations → expand Debug + Release"
echo "     → set both to 'AeroDrop' (the generated .xcconfig)"
echo "  4. Add all new source files to the Xcode target:"
echo "     AeroDrop/CXX/     → AeroServer.{h,cpp}  CertManager.{h,cpp}"
echo "     AeroDrop/Core/    → BonjourBridge.{h,.mm}  BridgeServer.{h,.mm}"
echo "     AeroDrop/Core/    → BonjourService.swift"
echo "     AeroDrop/UI/      → DropZoneView.swift  NeonProgressRing.swift"
echo "     AeroDrop/UI/      → PeerRowView.swift"
echo "     AeroDrop/         → AeroDrop-Bridging-Header.h  (Bridging Header only, NOT compiled)"
echo "  5. Delete ContentView.swift from the target (it's now unused)"
echo "  6. Build (⌘B) — should compile with zero errors"
echo ""
ok "Setup complete. Happy hacking! 🚀"
